# -*- coding: utf-8 -*-
"""Connect4 Game

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vzF6Z190NrSguHg-bnVycw-D7vLSDOUG
"""

import numpy as np

def personal_details():
    print("Programmed by Nurlan Najafzada")
    print("UFAZ, 12 December 2020")
personal_details()

print("\n")
print("Connect 4 Game")
print("\n")

ROW_COUNT = 6
COLUMN_COUNT = 7

def create_board():
    board = np.zeros((6,7))
    return board

def drop_piece(board, row, col, piece):
    board[row][col] = piece

def is_valid_location(board, col):
    return board[5][col] == 0

def get_next_open_row(board, col):
    for r in range(ROW_COUNT):
        if board[r][col] == 0:
            return r
def print_board(board):
    print(np.flip(board, 0))

board = create_board()
print(board)
game_over = False
turn = 0

while not game_over:
  
  # ask for player 1 input
  if turn == 0:
      col = int(input("Player 1 Turn:"))

      if is_valid_location(board, col):
          row = get_next_open_row(board, col)
          drop_piece(board, row, col, 1)

  # ask for player 2 input
  else:
      col = int(input("Player 2 Turn:"))

      if is_valid_location(board, col):
          row = get_next_open_row(board, col)
          drop_piece(board, row, col, 2)

  print_board(board)

  turn += 1
  turn = turn % 2